name = "ContinuousTimeMarkovChain"
uuid = "94d238af-ece3-4ea5-9f12-9f735918d5a2"
authors = ["Jonathan Miller jonathan.miller@fieldofnodes.com"]
version = "1.0.0-DEV"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
